# Application settings
instance_name = "integration-tests"

# Initialization settings
[init]
backend_type = "Kubernetes"

# Backend configuration
[backend]
# Kubernetes backend settings
[backend.kubernetes]
exec = "kind get kubeconfig --name kind" # Command to get kubeconfig for the Kind cluster
in_cluster = false                       # Whether to run in-cluster or not
namespace = "default"                    # Kubernetes namespace

# Repository settings for identities
[backend.kubernetes.identity_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "identity"
operation_timeout = "30s" # Timeout for operations on the actions repository

# Repository settings for principals
[backend.kubernetes.principal_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "principal"
operation_timeout = "30s" # Timeout for operations on the actions repository

# Repository settings for schemas
[backend.kubernetes.schema_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "schema"
operation_timeout = "30s" # Timeout for operations on the actions repository

# Repository settings for principal associations
[backend.kubernetes.principal_association_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "identity"
operation_timeout = "30s" # Timeout for operations on the actions repository

# Repository settings for principal associations
[backend.kubernetes.identity_provider_repository]
label_selector_key = "app.kubernetes.io/component"
label_selector_value = "identity"
operation_timeout = "30s" # Timeout for operations on the actions repository
