# Application settings
instance_name = "integration-tests"
deploy_environment = "development"

listen_address = "127.0.0.1:8888" # Address to listen on

# Initialization settings
[init]
backend_type = "Kubernetes"

# Backend configuration
[backend]
# Kubernetes backend settings
[backend.kubernetes]
exec = "kind get kubeconfig --name kind" # Command to get kubeconfig for the Kind cluster
in_cluster = false                       # Whether to run in-cluster or not
namespace = "default"                    # Kubernetes namespace
operation_timeout = "30s"                # Timeout for operations on the actions repository
resource_owner_label = "local.debug"     # Label to identify resources created by this instance

[opentelemetry.log_settings]
enabled = false

[opentelemetry.metrics_settings]
enabled = false

[opentelemetry.tracing_settings]
enabled = false

[token_settings]
# The settings below provided for testing purposes only
key_id = "public"
key = "0123456789ABCDEF0123456789ABCDEF"
content_encryption = "A128CBC-HS256"
audience = "boxer.sneaksanddata.com" # Expected audience for tokens
issuer = "boxer.sneaksanddata.com" # Expected audience for tokens

