apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "app.fullname" . }}-token-settings
  {{- with .Values.additionalAnnotations }}
  annotations:
        {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
type: Opaque
data:
  BOXER__TOKEN_SETTINGS__KEY: {{ (default (randAlphaNum 32) .Values.issuer.config.tokenSettings.key) | b64enc | quote }}
