apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.issuer.config.port | default 80 }}
      name: http
      targetPort: {{ .Values.issuer.config.port | default 80 }}
      protocol: TCP
  selector:
    {{- include "app.labels" $ | nindent 4 }}